import type { Metadata } from "next";
import "./../../globals.css";

import HeaderBar from "@/components/shared/HeaderBar";
import LeftSidebar from "@/components/shared/LeftSidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="w-screen h-screen">
            <HeaderBar />
            <div className="flex h-full w-full">
                <LeftSidebar />
                {children}
            </div>
        </div>
    );
}