import type { Metadata } from "next";
import "./../../globals.css";

import HeaderBar from "@/components/shared/HeaderBar";
import LeftSidebar from "@/components/shared/LeftSidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="w-screen h-screen bg-yellow-100">
                <HeaderBar />
                <main className="flex bg-yellow-100">
                    <LeftSidebar />
                    <section className="w-full">
                        {children}
                    </section>
                </main>
            </body>
        </html>
    );
}